FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npm rebuild bcrypt --build-from-source

COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
