FROM docker.io/library/caddy:2-builder AS builder

RUN xcaddy build \
  --with github.com/mholt/caddy-ratelimit

FROM docker.io/library/caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
