FROM docker.io/library/postgres:16

RUN apt-get update && apt-get install -y postgresql-16-pgaudit \
  && rm -rf /var/lib/apt/lists/*

RUN echo "CREATE EXTENSION IF NOT EXISTS pgaudit;" >> /docker-entrypoint-initdb.d/init.sql

COPY init.sh /docker-entrypoint-initdb.d/
