-- ============================================================================
-- KAPWA - MSWDO Norzagaray Social Welfare System
-- Oracle DDL, translated from the PostgreSQL schema in kapwa-schema.sql.
--
-- Import into Oracle SQL Developer Data Modeler:
--   File > Import > DDL File  ->  add kapwa-oracle.ddl
--   -> pick the Oracle Database version  ->  OK  ->  Compare Model  ->  Merge.
--   The CREATE TABLE block is kept apart from the ALTER TABLE ... and
--   CREATE INDEX statements, which is what the importer expects.
--
-- Contents: 61 tables, 49 foreign keys, 14 unique constraints,
--   11 check constraints, 87 indexes
--   (5 further indexes are listed as comments, see the INDEX section).
--
-- Type map (PostgreSQL -> Oracle):
--   uuid                        -> VARCHAR2(36)   the application generates UUIDv7
--   text                        -> VARCHAR2(4000)
--   varchar(n) / char(n)        -> VARCHAR2(n) / CHAR(n)
--   boolean                     -> NUMBER(1)      true = 1, false = 0
--   integer / bigint            -> NUMBER(10) / NUMBER(19)
--   numeric(p,s)                -> NUMBER(p,s)
--   timestamp / timestamptz     -> TIMESTAMP / TIMESTAMP WITH TIME ZONE
--   time                        -> TIMESTAMP      Oracle has no TIME type
--   jsonb / tsvector / <type>[] -> CLOB
--   bytea                       -> BLOB
--
-- text maps to VARCHAR2 rather than CLOB on purpose: Oracle cannot build a
-- B-tree index on a LOB (ORA-02327) and cannot compare one (ORA-00932), so
-- CLOB would invalidate the unique constraints, the check constraints and most
-- indexes. A generator guard enforces this. If you intend to *execute* this on
-- a real Oracle instance, promote the long-form content columns (HTML bodies
-- and the like) to CLOB -- none of them is indexed or checked.
--
-- Defaults: now() -> LOCALTIMESTAMP / SYSTIMESTAMP / SYSDATE, true/false -> 1/0,
--   uuid_generate_v7() dropped (application-generated), nextval(...) rewritten
--   as GENERATED BY DEFAULT AS IDENTITY.
--
-- Not translated (PostgreSQL-only, noted where relevant): row-level security
--   policies, the uuid-ossp / pgcrypto / pg_trgm extensions, the hash-chain
--   audit triggers, and the partial / GIN indexes listed as comments below.
--
-- No table or column comments exist in the source schema, so there is no
-- COMMENT ON section.
--
-- Regenerate: DB_NAME=<live db> python3 gen-oracle-ddl.py   (this directory)
-- ============================================================================

-- =========================== TABLES ===========================

CREATE TABLE access_card_seq (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    year NUMBER(10) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT access_card_seq_pkey PRIMARY KEY (id)
);

CREATE TABLE access_card_services (
    id VARCHAR2(36) NOT NULL,
    access_card_code VARCHAR2(4000),
    service_date DATE NOT NULL,
    service_rendered VARCHAR2(4000) NOT NULL,
    cost NUMBER(12, 2),
    agency VARCHAR2(4000),
    agency_id VARCHAR2(36),
    worker_name_sign VARCHAR2(4000),
    intervention_id VARCHAR2(36),
    category VARCHAR2(4000),
    logged_by VARCHAR2(36),
    source_barangay VARCHAR2(4000),
    CONSTRAINT access_card_services_pkey PRIMARY KEY (id)
);

CREATE TABLE agencies (
    id VARCHAR2(36) NOT NULL,
    code VARCHAR2(10) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    type VARCHAR2(50),
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT agencies_pkey PRIMARY KEY (id),
    CONSTRAINT agencies_code_key UNIQUE (code)
);

CREATE TABLE agency_contacts (
    id VARCHAR2(36) NOT NULL,
    agency_id VARCHAR2(36) NOT NULL,
    contact_type VARCHAR2(50) NOT NULL,
    value VARCHAR2(4000) NOT NULL,
    is_primary NUMBER(1),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT agency_contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis_run_clusters (
    id VARCHAR2(36) NOT NULL,
    run_id VARCHAR2(36) NOT NULL,
    cluster_index NUMBER(10) NOT NULL,
    "size" NUMBER(10) NOT NULL,
    centroid CLOB,
    profile CLOB,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT analysis_run_clusters_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis_run_members (
    id VARCHAR2(36) NOT NULL,
    run_id VARCHAR2(36) NOT NULL,
    household_id VARCHAR2(36) NOT NULL,
    cluster_index NUMBER(10) NOT NULL,
    distance NUMBER(12, 6),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT analysis_run_members_pkey PRIMARY KEY (id)
);

CREATE TABLE analysis_runs (
    id VARCHAR2(36) NOT NULL,
    model VARCHAR2(4000) DEFAULT 'household_clustering' NOT NULL,
    status VARCHAR2(20) DEFAULT 'completed' NOT NULL,
    params CLOB,
    metrics CLOB,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(36),
    error VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT analysis_runs_pkey PRIMARY KEY (id),
    CONSTRAINT analysis_runs_status_check CHECK (((status) IN ('completed', 'failed')))
);

CREATE TABLE announcements (
    id VARCHAR2(36) NOT NULL,
    title VARCHAR2(4000) NOT NULL,
    slug VARCHAR2(4000) NOT NULL,
    excerpt VARCHAR2(4000) DEFAULT '' NOT NULL,
    body_html VARCHAR2(4000) DEFAULT '' NOT NULL,
    body_text VARCHAR2(4000) DEFAULT '' NOT NULL,
    status VARCHAR2(4000) DEFAULT 'draft' NOT NULL,
    pinned NUMBER(1) DEFAULT 0 NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR2(36),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT announcements_pkey PRIMARY KEY (id),
    CONSTRAINT announcements_slug_key UNIQUE (slug),
    CONSTRAINT announcements_status_check CHECK ((status IN ('draft', 'published')))
);

CREATE TABLE audit_log (
    id VARCHAR2(36) NOT NULL,
    action VARCHAR2(4000) NOT NULL,
    reference_id VARCHAR2(4000),
    user_id VARCHAR2(4000),
    details CLOB,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE beneficiaries (
    id VARCHAR2(36) NOT NULL,
    person_id VARCHAR2(36),
    user_id VARCHAR2(36),
    household_id VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    hash VARCHAR2(4000),
    prev_hash VARCHAR2(4000),
    CONSTRAINT beneficiaries_pkey PRIMARY KEY (id)
);

CREATE TABLE beneficiary_claimants (
    id VARCHAR2(36) NOT NULL,
    beneficiary_id VARCHAR2(36) NOT NULL,
    claimant_id VARCHAR2(36) NOT NULL,
    relationship VARCHAR2(4000) NOT NULL,
    authorization_url VARCHAR2(4000),
    calendar_year NUMBER(10),
    is_primary NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT beneficiary_claimants_pkey PRIMARY KEY (id)
);

CREATE TABLE beneficiary_roles (
    id VARCHAR2(36) NOT NULL,
    person_id VARCHAR2(36) NOT NULL,
    household_id VARCHAR2(36),
    user_id VARCHAR2(36),
    consent_status VARCHAR2(4000) DEFAULT 'active',
    access_card_code VARCHAR2(4000),
    category VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT beneficiary_roles_pkey PRIMARY KEY (id),
    CONSTRAINT beneficiary_roles_access_card_code_key UNIQUE (access_card_code)
);

CREATE TABLE case_assistances (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    assistance_type VARCHAR2(50) NOT NULL,
    amount NUMBER(12, 2),
    "mode" VARCHAR2(50),
    source_of_fund VARCHAR2(100),
    legislator_specify VARCHAR2(255),
    details CLOB,
    approved_by_signature VARCHAR2(4000),
    approved_by_role VARCHAR2(50),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_assistances_pkey PRIMARY KEY (id)
);

CREATE TABLE case_compliance_items (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    household_member_id VARCHAR2(36),
    compliance_type VARCHAR2(4000),
    due_date DATE NOT NULL,
    month_label VARCHAR2(4000),
    met NUMBER(1) DEFAULT 0,
    met_at TIMESTAMP,
    met_by VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_compliance_items_pkey PRIMARY KEY (id),
    CONSTRAINT case_compliance_items_compliance_type_check CHECK (((compliance_type) IN ('school_attendance', 'health_checkup', 'fds')))
);

CREATE TABLE case_control_counters (
    year NUMBER(10) NOT NULL,
    last_seq NUMBER(10) DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_control_counters_pkey PRIMARY KEY (year)
);

CREATE TABLE case_event_reminders (
    id VARCHAR2(36) NOT NULL,
    event_id VARCHAR2(36) NOT NULL,
    offset_minutes NUMBER(10) NOT NULL,
    channel VARCHAR2(16) NOT NULL,
    sent_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_event_reminders_pkey PRIMARY KEY (id)
);

CREATE TABLE case_events (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    event_type VARCHAR2(32) NOT NULL,
    attended NUMBER(1),
    title VARCHAR2(4000),
    venue VARCHAR2(4000),
    event_date DATE NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    notes VARCHAR2(4000),
    status VARCHAR2(32) DEFAULT 'planned' NOT NULL,
    created_by VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_events_pkey PRIMARY KEY (id)
);

CREATE TABLE case_follow_up_visits (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    visit_date DATE NOT NULL,
    visit_type VARCHAR2(4000) NOT NULL,
    notes VARCHAR2(4000),
    outcome VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_follow_up_visits_pkey PRIMARY KEY (id)
);

CREATE TABLE case_history (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(4000) NOT NULL,
    from_status VARCHAR2(4000),
    to_status VARCHAR2(4000) NOT NULL,
    changed_by_role VARCHAR2(4000),
    changed_by_id VARCHAR2(4000),
    remarks VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    transition_type VARCHAR2(4000) DEFAULT 'standard' NOT NULL,
    override_reason VARCHAR2(4000),
    CONSTRAINT PK_case_history PRIMARY KEY (id)
);

CREATE TABLE case_interventions (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(4000) NOT NULL,
    program_id VARCHAR2(36),
    service_name VARCHAR2(4000) NOT NULL,
    category VARCHAR2(4000),
    delivery_date DATE,
    amount NUMBER(12, 2),
    mode_of_delivery VARCHAR2(4000),
    fund_source VARCHAR2(4000),
    notes VARCHAR2(4000),
    delivered_by VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    created_by VARCHAR2(36),
    intervention_type VARCHAR2(4000),
    program_enrollment_id VARCHAR2(36),
    CONSTRAINT case_interventions_pkey PRIMARY KEY (id)
);

CREATE TABLE case_payouts (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    cycle_no VARCHAR2(4000),
    scheduled_at DATE NOT NULL,
    amount NUMBER(12, 2),
    status VARCHAR2(20) DEFAULT 'scheduled',
    notified_at TIMESTAMP,
    notified_by VARCHAR2(36),
    remarks VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_payouts_pkey PRIMARY KEY (id),
    CONSTRAINT case_payouts_status_check CHECK (((status) IN ('scheduled', 'completed', 'missed', 'cancelled')))
);

CREATE TABLE case_referrals (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    agency VARCHAR2(255),
    status VARCHAR2(50),
    notes VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    reason VARCHAR2(4000) NOT NULL,
    contact_info VARCHAR2(4000),
    created_by VARCHAR2(36),
    CONSTRAINT case_referrals_pkey PRIMARY KEY (id)
);

CREATE TABLE case_requirements (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    requirement_key VARCHAR2(100) NOT NULL,
    met NUMBER(1),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_requirements_pkey PRIMARY KEY (id)
);

CREATE TABLE case_step_locks (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(4000) NOT NULL,
    step_key VARCHAR2(4000) NOT NULL,
    locked_by VARCHAR2(36),
    locked_by_name VARCHAR2(4000),
    locked_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT case_step_locks_pkey PRIMARY KEY (id),
    CONSTRAINT uq_case_step_locks_case_step_key UNIQUE (case_id, step_key)
);

CREATE TABLE cases (
    id VARCHAR2(36) NOT NULL,
    control_no VARCHAR2(4000) NOT NULL,
    beneficiary_id VARCHAR2(36),
    renewal_of_case_id VARCHAR2(36),
    service_requested CLOB,
    requirements_checklist CLOB,
    status VARCHAR2(4000) DEFAULT 'enrolled',
    certificate_url VARCHAR2(4000),
    petty_cash_voucher_url VARCHAR2(4000),
    assigned_worker_id VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    problems_presented VARCHAR2(4000),
    social_worker_assessment VARCHAR2(4000),
    client_category VARCHAR2(4000),
    case_category VARCHAR2(4000),
    court_docket_number VARCHAR2(4000),
    crisis_mode NUMBER(1) DEFAULT 0 NOT NULL,
    discernment_assessed_at DATE,
    discernment_result VARCHAR2(4000),
    discernment_notes VARCHAR2(4000),
    protection_order_type VARCHAR2(4000),
    protection_order_issued_at DATE,
    protection_order_issued_by VARCHAR2(4000),
    protection_order_notes VARCHAR2(4000),
    enrollments_not_needed NUMBER(1) DEFAULT 0 NOT NULL,
    solo_parent_id_issued_date DATE,
    solo_parent_id_number VARCHAR2(4000),
    solo_parent_notes VARCHAR2(4000),
    adoption_dvc_date DATE,
    adoption_case_study_date DATE,
    adoption_cdclaa_received NUMBER(1),
    adoption_notes VARCHAR2(4000),
    nature_of_service CLOB,
    financial_subsidies CLOB,
    amount_assistance NUMBER(12, 2),
    mode_financial_assistance VARCHAR2(4000),
    source_of_fund VARCHAR2(4000),
    legislator_specify VARCHAR2(4000),
    other_assistance CLOB,
    interviewed_by VARCHAR2(4000),
    assigned_worker_name VARCHAR2(4000),
    client_signature VARCHAR2(4000),
    approved_by_signature VARCHAR2(4000),
    approved_by_role VARCHAR2(4000),
    referral_not_needed NUMBER(1) DEFAULT 0 NOT NULL,
    intervention_not_needed NUMBER(1) DEFAULT 0 NOT NULL,
    self_reliance_plan VARCHAR2(4000),
    referrals CLOB,
    follow_up_date DATE,
    exit_notes VARCHAR2(4000),
    frva_score NUMBER(5, 2),
    swdi_score NUMBER(5, 2),
    family_dialogue_notes VARCHAR2(4000),
    self_reliance_level NUMBER(10),
    sustainability_plan VARCHAR2(4000),
    transition_date DATE,
    closure_outcome VARCHAR2(4000),
    closure_date DATE,
    follow_up_visits CLOB,
    approved_by_name VARCHAR2(4000),
    hash VARCHAR2(4000),
    prev_hash VARCHAR2(4000),
    CONSTRAINT cases_pkey PRIMARY KEY (id),
    CONSTRAINT cases_control_no_key UNIQUE (control_no),
    CONSTRAINT cases_status_check CHECK ((status IN ('enrolled', 'assessed', 'in_review', 'active', 'transitioning', 'closed', 'aftercare')))
);

CREATE TABLE chat_messages (
    id VARCHAR2(36) NOT NULL,
    sender_id VARCHAR2(4000) NOT NULL,
    recipient_id VARCHAR2(4000) NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    conversation_id VARCHAR2(4000) NOT NULL,
    is_read NUMBER(1) DEFAULT 0,
    read_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    sender_name VARCHAR2(4000),
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE consent_ledger (
    id VARCHAR2(36) NOT NULL,
    beneficiary_id VARCHAR2(36),
    purpose VARCHAR2(4000),
    channel VARCHAR2(4000),
    status VARCHAR2(4000) DEFAULT 'active',
    granted_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    revoked_at TIMESTAMP,
    revoked_reason VARCHAR2(4000),
    hash VARCHAR2(4000),
    prev_hash VARCHAR2(4000),
    CONSTRAINT consent_ledger_pkey PRIMARY KEY (id)
);

CREATE TABLE contact_messages (
    id VARCHAR2(36) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    subject VARCHAR2(200),
    message VARCHAR2(4000) NOT NULL,
    status VARCHAR2(10) DEFAULT 'new' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE csr_reports (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    control_no VARCHAR2(4000) NOT NULL,
    social_worker_name VARCHAR2(4000) NOT NULL,
    social_worker_position VARCHAR2(4000),
    referral_origin VARCHAR2(4000),
    reason_for_referral VARCHAR2(4000),
    problem_presented VARCHAR2(4000),
    family_background VARCHAR2(4000),
    socio_economic_profile VARCHAR2(4000),
    assessment_analysis VARCHAR2(4000),
    recommendation VARCHAR2(4000),
    intervention_plan VARCHAR2(4000),
    client_signature_url VARCHAR2(4000),
    worker_signature_url VARCHAR2(4000),
    finalized NUMBER(1) DEFAULT 0,
    created_by VARCHAR2(4000) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT csr_reports_pkey PRIMARY KEY (id),
    CONSTRAINT csr_reports_control_no_key UNIQUE (control_no)
);

CREATE TABLE document_vault (
    id VARCHAR2(36) NOT NULL,
    file_name VARCHAR2(4000) NOT NULL,
    original_name VARCHAR2(4000),
    mime_type VARCHAR2(4000),
    file_size NUMBER(10) DEFAULT 0,
    case_id VARCHAR2(36),
    beneficiary_id VARCHAR2(36),
    category VARCHAR2(4000),
    notes VARCHAR2(4000),
    uploaded_by VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    irf_id VARCHAR2(36),
    announcement_id VARCHAR2(36),
    verified_at TIMESTAMP,
    verified_by VARCHAR2(36),
    requirement_key VARCHAR2(4000),
    CONSTRAINT document_vault_pkey PRIMARY KEY (id)
);

CREATE TABLE form_version_history (
    id VARCHAR2(36) NOT NULL,
    program_id VARCHAR2(36) NOT NULL,
    form_template CLOB NOT NULL,
    version NUMBER(10) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT form_version_history_pkey PRIMARY KEY (id)
);

CREATE TABLE household_memberships (
    id VARCHAR2(36) NOT NULL,
    person_id VARCHAR2(36) NOT NULL,
    household_id VARCHAR2(36),
    relationship VARCHAR2(4000) NOT NULL,
    is_primary NUMBER(1) DEFAULT 0,
    status VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    status_reason VARCHAR2(4000),
    CONSTRAINT household_memberships_pkey PRIMARY KEY (id)
);

CREATE TABLE households (
    id VARCHAR2(36) NOT NULL,
    primary_beneficiary_id VARCHAR2(36),
    barangay VARCHAR2(4000),
    estimated_income NUMBER(12, 2),
    verified_by VARCHAR2(4000),
    access_card_code VARCHAR2(4000),
    verified_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    nhts_pr_id VARCHAR2(4000),
    CONSTRAINT households_pkey PRIMARY KEY (id)
);

CREATE TABLE idempotency_keys (
    id VARCHAR2(36) NOT NULL,
    key VARCHAR2(4000) NOT NULL,
    result CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id),
    CONSTRAINT idempotency_keys_key_key UNIQUE (key)
);

CREATE TABLE inter_agency_referrals (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36),
    person_id VARCHAR2(36) NOT NULL,
    from_agency_id VARCHAR2(36) NOT NULL,
    to_agency_id VARCHAR2(36) NOT NULL,
    status VARCHAR2(4000) DEFAULT 'referred' NOT NULL,
    reason VARCHAR2(4000) NOT NULL,
    notes VARCHAR2(4000),
    legal_basis_code VARCHAR2(4000) NOT NULL,
    consent_ledger_id VARCHAR2(36),
    outcome VARCHAR2(4000),
    received_at TIMESTAMP,
    actioned_at TIMESTAMP,
    closed_at TIMESTAMP,
    declined_reason VARCHAR2(4000),
    created_by VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT inter_agency_referrals_pkey PRIMARY KEY (id),
    CONSTRAINT inter_agency_referrals_status_check CHECK ((status IN ('referred', 'received', 'actioned', 'closed', 'declined')))
);

CREATE TABLE intervention_required_documents (
    id VARCHAR2(36) NOT NULL,
    intervention_type VARCHAR2(32) NOT NULL,
    document_key VARCHAR2(64) NOT NULL,
    mandatory NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT intervention_required_documents_pkey PRIMARY KEY (id)
);

CREATE TABLE irf_blotter_seq (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    year NUMBER(10) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT irf_blotter_seq_pkey PRIMARY KEY (id)
);

CREATE TABLE irf_cases (
    id VARCHAR2(36) NOT NULL,
    blotter_entry_number VARCHAR2(4000) NOT NULL,
    case_category VARCHAR2(4000) NOT NULL,
    datetime_reported TIMESTAMP,
    datetime_incident TIMESTAMP,
    item_a_reporting_person CLOB,
    item_b_person_reported CLOB,
    encrypted_narration BLOB,
    case_disposition VARCHAR2(4000),
    msdw_signature_url VARCHAR2(4000),
    reporting_signature_url VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    key_wraps CLOB,
    key_version NUMBER(10) DEFAULT 1,
    dismissal_reason VARCHAR2(4000),
    case_id VARCHAR2(36),
    CONSTRAINT irf_cases_pkey PRIMARY KEY (id),
    CONSTRAINT irf_cases_blotter_entry_number_key UNIQUE (blotter_entry_number)
);

CREATE TABLE migrations (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    timestamp NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    CONSTRAINT migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE notification_preferences (
    id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(4000) NOT NULL,
    channel VARCHAR2(4000) NOT NULL,
    category VARCHAR2(4000) NOT NULL,
    opted_in NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT notification_preferences_pkey PRIMARY KEY (id)
);

CREATE TABLE notifications (
    id VARCHAR2(36) NOT NULL,
    recipient_id VARCHAR2(4000) NOT NULL,
    title VARCHAR2(4000) NOT NULL,
    message VARCHAR2(4000) NOT NULL,
    channel VARCHAR2(4000) DEFAULT 'in_app',
    phone VARCHAR2(4000),
    sent NUMBER(1) DEFAULT 0,
    sent_at TIMESTAMP,
    is_read NUMBER(1) DEFAULT 0,
    category VARCHAR2(4000) DEFAULT 'system',
    reference_id VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    consent_skipped NUMBER(1) DEFAULT 0,
    email VARCHAR2(4000),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE office_events (
    id VARCHAR2(36) NOT NULL,
    title VARCHAR2(4000) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    repeat_rule CLOB,
    visible_to VARCHAR2(32) DEFAULT 'staff' NOT NULL,
    location VARCHAR2(4000),
    owner_id VARCHAR2(36) NOT NULL,
    notes VARCHAR2(4000),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT office_events_pkey PRIMARY KEY (id)
);

CREATE TABLE otp_codes (
    id VARCHAR2(36) NOT NULL,
    phone VARCHAR2(4000) NOT NULL,
    code VARCHAR2(4000) NOT NULL,
    verified NUMBER(1) DEFAULT 0,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT otp_codes_pkey PRIMARY KEY (id)
);

CREATE TABLE person_addresses (
    id VARCHAR2(36) NOT NULL,
    person_id VARCHAR2(36) NOT NULL,
    address_type VARCHAR2(50) NOT NULL,
    barangay VARCHAR2(255),
    city VARCHAR2(255),
    province VARCHAR2(255),
    postal VARCHAR2(20),
    is_primary NUMBER(1),
    "raw" VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    street VARCHAR2(4000),
    region VARCHAR2(4000),
    CONSTRAINT person_addresses_pkey PRIMARY KEY (id)
);

CREATE TABLE person_contacts (
    id VARCHAR2(36) NOT NULL,
    person_id VARCHAR2(36) NOT NULL,
    contact_type VARCHAR2(50) NOT NULL,
    value VARCHAR2(4000) NOT NULL,
    is_primary NUMBER(1),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT person_contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE persons (
    id VARCHAR2(36) NOT NULL,
    surname VARCHAR2(4000) NOT NULL,
    first_name VARCHAR2(4000) NOT NULL,
    middle_name VARCHAR2(4000),
    gender VARCHAR2(4000),
    dob DATE NOT NULL,
    philsys_number VARCHAR2(4000),
    place_of_birth VARCHAR2(4000),
    civil_status VARCHAR2(4000),
    occupation VARCHAR2(4000),
    estimated_monthly_income NUMBER(12, 2),
    search_vector CLOB,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    extension VARCHAR2(4000),
    CONSTRAINT persons_pkey PRIMARY KEY (id),
    CONSTRAINT persons_philsys_number_key UNIQUE (philsys_number),
    CONSTRAINT persons_gender_check CHECK ((gender IN ('Male', 'Female')))
);

CREATE TABLE program_enrollments (
    id VARCHAR2(36) NOT NULL,
    case_id VARCHAR2(36) NOT NULL,
    program_id VARCHAR2(36) NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR2(4000) DEFAULT 'active' NOT NULL,
    created_by VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT program_enrollments_pkey PRIMARY KEY (id),
    CONSTRAINT uq_program_enrollments_case_program UNIQUE (case_id, program_id)
);

CREATE TABLE program_fund_sources (
    id VARCHAR2(36) NOT NULL,
    program_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT program_fund_sources_pkey PRIMARY KEY (id)
);

CREATE TABLE program_required_documents (
    id VARCHAR2(36) NOT NULL,
    program_id VARCHAR2(36) NOT NULL,
    document_key VARCHAR2(100) NOT NULL,
    mandatory NUMBER(1),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT program_required_documents_pkey PRIMARY KEY (id)
);

CREATE TABLE program_services (
    id VARCHAR2(36) NOT NULL,
    program_id VARCHAR2(36) NOT NULL,
    intervention_type VARCHAR2(4000) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT program_services_pkey PRIMARY KEY (id),
    CONSTRAINT uq_program_services_program_type UNIQUE (program_id, intervention_type)
);

CREATE TABLE programs (
    id VARCHAR2(36) NOT NULL,
    name VARCHAR2(4000) NOT NULL,
    category VARCHAR2(4000),
    approval_workflow CLOB,
    form_template CLOB,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    program_type VARCHAR2(4000),
    legal_basis VARCHAR2(4000),
    form_version NUMBER(10) DEFAULT 1,
    CONSTRAINT programs_pkey PRIMARY KEY (id)
);

CREATE TABLE referrals (
    id VARCHAR2(36) NOT NULL,
    coordinator_id VARCHAR2(36) NOT NULL,
    barangay VARCHAR2(4000) NOT NULL,
    surname VARCHAR2(4000),
    first_name VARCHAR2(4000),
    middle_name VARCHAR2(4000),
    extension VARCHAR2(4000),
    gender VARCHAR2(4000),
    dob DATE,
    address CLOB,
    phone VARCHAR2(4000),
    reason VARCHAR2(4000) NOT NULL,
    status VARCHAR2(4000) DEFAULT 'pending',
    decline_reason VARCHAR2(4000),
    case_id VARCHAR2(36),
    person_id VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT referrals_pkey PRIMARY KEY (id),
    CONSTRAINT referrals_status_check CHECK ((status IN ('pending', 'accepted', 'declined')))
);

CREATE TABLE reminder_settings (
    id VARCHAR2(36) NOT NULL,
    scope VARCHAR2(16) NOT NULL,
    user_id VARCHAR2(36),
    event_type VARCHAR2(32) NOT NULL,
    offsets CLOB NOT NULL,
    updated_by VARCHAR2(36),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT reminder_settings_pkey PRIMARY KEY (id),
    CONSTRAINT reminder_settings_check CHECK (((((scope) = 'system') AND (user_id IS NULL)) OR (((scope) = 'worker') AND (user_id IS NOT NULL)))),
    CONSTRAINT reminder_settings_scope_check CHECK (((scope) IN ('system', 'worker')))
);

CREATE TABLE sync_queue (
    id VARCHAR2(36) NOT NULL,
    device_id VARCHAR2(4000) NOT NULL,
    table_name VARCHAR2(4000) NOT NULL,
    record_id VARCHAR2(4000) NOT NULL,
    operation VARCHAR2(4000) NOT NULL,
    payload CLOB,
    client_updated_at TIMESTAMP,
    status VARCHAR2(4000) DEFAULT 'pending',
    idempotency_key VARCHAR2(4000),
    conflict_reason VARCHAR2(4000),
    resolved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT sync_queue_pkey PRIMARY KEY (id)
);

CREATE TABLE team_invites (
    id VARCHAR2(36) NOT NULL,
    from_user_id VARCHAR2(36) NOT NULL,
    to_user_id VARCHAR2(36) NOT NULL,
    invite_date DATE NOT NULL,
    block_type VARCHAR2(32) NOT NULL,
    note VARCHAR2(4000),
    status VARCHAR2(16) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    responded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT team_invites_pkey PRIMARY KEY (id)
);

CREATE TABLE team_schedule_blocks (
    id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    block_date DATE NOT NULL,
    block_type VARCHAR2(32) NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    note VARCHAR2(4000),
    created_by VARCHAR2(36),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    source VARCHAR2(32) DEFAULT 'manual' NOT NULL,
    source_ref VARCHAR2(36),
    visible_to VARCHAR2(32) DEFAULT 'team' NOT NULL,
    end_date DATE,
    CONSTRAINT team_schedule_blocks_pkey PRIMARY KEY (id),
    CONSTRAINT chk_team_schedule_blocks_end_date CHECK (((end_date IS NULL) OR (end_date >= block_date)))
);

CREATE TABLE team_status (
    id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    status VARCHAR2(32) NOT NULL,
    note VARCHAR2(4000),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    visible_to VARCHAR2(32) DEFAULT 'team' NOT NULL,
    CONSTRAINT team_status_pkey PRIMARY KEY (id),
    CONSTRAINT team_status_user_id_key UNIQUE (user_id)
);

CREATE TABLE user_barangay_assignments (
    id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    barangay VARCHAR2(255) NOT NULL,
    is_primary NUMBER(1),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT user_barangay_assignments_pkey PRIMARY KEY (id)
);

CREATE TABLE user_tokens (
    id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(36) NOT NULL,
    purpose VARCHAR2(50) NOT NULL,
    token VARCHAR2(4000) NOT NULL,
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    meta CLOB,
    CONSTRAINT user_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
    id VARCHAR2(36) NOT NULL,
    email VARCHAR2(4000) NOT NULL,
    password VARCHAR2(4000) NOT NULL,
    role VARCHAR2(4000) DEFAULT 'social_worker',
    first_name VARCHAR2(4000),
    middle_name VARCHAR2(4000),
    last_name VARCHAR2(4000),
    name_extension VARCHAR2(4000),
    phone VARCHAR2(4000),
    is_active NUMBER(1) DEFAULT 1,
    device_id VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    person_id VARCHAR2(36),
    pending_person_id VARCHAR2(36),
    person_link_code VARCHAR2(4000),
    person_link_code_expires_at TIMESTAMP,
    mfa_secret VARCHAR2(4000),
    mfa_enabled NUMBER(1) DEFAULT 0,
    mfa_method VARCHAR2(4000),
    email_otp_code VARCHAR2(4000),
    email_otp_expires_at TIMESTAMP,
    token_version NUMBER(10) DEFAULT 0,
    email_verified NUMBER(1) DEFAULT 1,
    must_change_password NUMBER(1) DEFAULT 0 NOT NULL,
    agency_id VARCHAR2(36),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE version_vectors (
    id VARCHAR2(36) NOT NULL,
    device_id VARCHAR2(4000) NOT NULL,
    table_name VARCHAR2(4000) NOT NULL,
    local_version NUMBER(10) DEFAULT 0,
    server_version NUMBER(10) DEFAULT 0,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    CONSTRAINT version_vectors_pkey PRIMARY KEY (id),
    CONSTRAINT version_vectors_device_id_table_name_key UNIQUE (device_id, table_name)
);


-- ====================== FOREIGN KEYS ============================

ALTER TABLE access_card_services ADD CONSTRAINT access_card_services_logged_by_fkey
    FOREIGN KEY (logged_by) REFERENCES users(id);
ALTER TABLE analysis_run_clusters ADD CONSTRAINT analysis_run_clusters_run_id_fkey
    FOREIGN KEY (run_id) REFERENCES analysis_runs(id) ON DELETE CASCADE;
ALTER TABLE analysis_run_members ADD CONSTRAINT analysis_run_members_household_id_fkey
    FOREIGN KEY (household_id) REFERENCES households(id);
ALTER TABLE analysis_run_members ADD CONSTRAINT analysis_run_members_run_id_fkey
    FOREIGN KEY (run_id) REFERENCES analysis_runs(id) ON DELETE CASCADE;
ALTER TABLE analysis_runs ADD CONSTRAINT analysis_runs_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE beneficiary_claimants ADD CONSTRAINT beneficiary_claimants_beneficiary_id_fkey
    FOREIGN KEY (beneficiary_id) REFERENCES persons(id);
ALTER TABLE beneficiary_claimants ADD CONSTRAINT beneficiary_claimants_claimant_id_fkey
    FOREIGN KEY (claimant_id) REFERENCES persons(id);
ALTER TABLE beneficiary_roles ADD CONSTRAINT beneficiary_roles_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES persons(id);
ALTER TABLE case_compliance_items ADD CONSTRAINT case_compliance_items_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id);
ALTER TABLE case_compliance_items ADD CONSTRAINT case_compliance_items_household_member_id_fkey
    FOREIGN KEY (household_member_id) REFERENCES persons(id);
ALTER TABLE case_compliance_items ADD CONSTRAINT case_compliance_items_met_by_fkey
    FOREIGN KEY (met_by) REFERENCES users(id);
ALTER TABLE case_event_reminders ADD CONSTRAINT case_event_reminders_event_id_fkey
    FOREIGN KEY (event_id) REFERENCES case_events(id) ON DELETE CASCADE;
ALTER TABLE case_events ADD CONSTRAINT case_events_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
ALTER TABLE case_events ADD CONSTRAINT case_events_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE case_interventions ADD CONSTRAINT case_interventions_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE case_payouts ADD CONSTRAINT case_payouts_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id);
ALTER TABLE case_payouts ADD CONSTRAINT case_payouts_notified_by_fkey
    FOREIGN KEY (notified_by) REFERENCES users(id);
ALTER TABLE case_referrals ADD CONSTRAINT case_referrals_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE cases ADD CONSTRAINT cases_beneficiary_id_fkey
    FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id);
ALTER TABLE form_version_history ADD CONSTRAINT form_version_history_program_id_fkey
    FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
ALTER TABLE household_memberships ADD CONSTRAINT household_memberships_household_id_fkey
    FOREIGN KEY (household_id) REFERENCES households(id);
ALTER TABLE household_memberships ADD CONSTRAINT household_memberships_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES persons(id);
ALTER TABLE households ADD CONSTRAINT households_primary_beneficiary_id_fkey
    FOREIGN KEY (primary_beneficiary_id) REFERENCES beneficiaries(id);
ALTER TABLE inter_agency_referrals ADD CONSTRAINT inter_agency_referrals_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id);
ALTER TABLE inter_agency_referrals ADD CONSTRAINT inter_agency_referrals_consent_ledger_id_fkey
    FOREIGN KEY (consent_ledger_id) REFERENCES consent_ledger(id);
ALTER TABLE inter_agency_referrals ADD CONSTRAINT inter_agency_referrals_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE inter_agency_referrals ADD CONSTRAINT inter_agency_referrals_from_agency_id_fkey
    FOREIGN KEY (from_agency_id) REFERENCES agencies(id);
ALTER TABLE inter_agency_referrals ADD CONSTRAINT inter_agency_referrals_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES persons(id);
ALTER TABLE inter_agency_referrals ADD CONSTRAINT inter_agency_referrals_to_agency_id_fkey
    FOREIGN KEY (to_agency_id) REFERENCES agencies(id);
ALTER TABLE irf_cases ADD CONSTRAINT irf_cases_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id);
ALTER TABLE office_events ADD CONSTRAINT office_events_owner_id_fkey
    FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE program_enrollments ADD CONSTRAINT program_enrollments_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id);
ALTER TABLE program_enrollments ADD CONSTRAINT program_enrollments_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE program_enrollments ADD CONSTRAINT program_enrollments_program_id_fkey
    FOREIGN KEY (program_id) REFERENCES programs(id);
ALTER TABLE program_services ADD CONSTRAINT program_services_program_id_fkey
    FOREIGN KEY (program_id) REFERENCES programs(id);
ALTER TABLE referrals ADD CONSTRAINT referrals_case_id_fkey
    FOREIGN KEY (case_id) REFERENCES cases(id);
ALTER TABLE referrals ADD CONSTRAINT referrals_coordinator_id_fkey
    FOREIGN KEY (coordinator_id) REFERENCES users(id);
ALTER TABLE referrals ADD CONSTRAINT referrals_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES persons(id);
ALTER TABLE reminder_settings ADD CONSTRAINT reminder_settings_updated_by_fkey
    FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE reminder_settings ADD CONSTRAINT reminder_settings_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE team_invites ADD CONSTRAINT team_invites_from_user_id_fkey
    FOREIGN KEY (from_user_id) REFERENCES users(id);
ALTER TABLE team_invites ADD CONSTRAINT team_invites_to_user_id_fkey
    FOREIGN KEY (to_user_id) REFERENCES users(id);
ALTER TABLE team_schedule_blocks ADD CONSTRAINT fk_blocks_source_ref
    FOREIGN KEY (source_ref) REFERENCES case_events(id) ON DELETE SET NULL;
ALTER TABLE team_schedule_blocks ADD CONSTRAINT team_schedule_blocks_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE team_schedule_blocks ADD CONSTRAINT team_schedule_blocks_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE team_status ADD CONSTRAINT team_status_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users ADD CONSTRAINT users_agency_id_fkey
    FOREIGN KEY (agency_id) REFERENCES agencies(id);
ALTER TABLE users ADD CONSTRAINT users_person_id_fkey
    FOREIGN KEY (person_id) REFERENCES persons(id);


-- ========================== INDEXES =============================

CREATE INDEX idx_acs_agency_date ON access_card_services (agency_id, service_date);
CREATE INDEX idx_acs_code ON access_card_services (access_card_code);
CREATE INDEX idx_acs_intervention ON access_card_services (intervention_id);
CREATE INDEX idx_agency_contacts_agency ON agency_contacts (agency_id);
CREATE INDEX idx_run_cluster_run ON analysis_run_clusters (run_id, cluster_index);
CREATE INDEX idx_run_member_cluster ON analysis_run_members (run_id, cluster_index);
CREATE UNIQUE INDEX idx_run_member_unique ON analysis_run_members (run_id, household_id);
CREATE INDEX idx_runs_created ON analysis_runs (created_at);
CREATE INDEX idx_audit_log_action ON audit_log (action);
CREATE INDEX idx_audit_log_reference ON audit_log (reference_id);
CREATE INDEX idx_beneficiary_person ON beneficiaries (person_id);
CREATE INDEX idx_beneficiary_user ON beneficiaries (user_id);
CREATE INDEX idx_bc_beneficiary ON beneficiary_claimants (beneficiary_id);
CREATE INDEX idx_bc_claimant ON beneficiary_claimants (claimant_id);
CREATE UNIQUE INDEX idx_bc_unique_primary ON beneficiary_claimants (beneficiary_id, claimant_id);
CREATE UNIQUE INDEX uq_beneficiary_roles_access_card_code ON beneficiary_roles (access_card_code);
CREATE INDEX idx_case_assistances_case ON case_assistances (case_id);
CREATE INDEX idx_compliance_case ON case_compliance_items (case_id);
CREATE UNIQUE INDEX idx_compliance_dedupe ON case_compliance_items (case_id, household_member_id, compliance_type, due_date);
CREATE INDEX idx_compliance_due ON case_compliance_items (due_date);
CREATE UNIQUE INDEX uq_case_event_reminders ON case_event_reminders (event_id, offset_minutes, channel);
CREATE INDEX idx_case_events_case ON case_events (case_id);
CREATE INDEX idx_case_events_date ON case_events (event_date);
CREATE INDEX idx_case_events_status_date ON case_events (status, event_date);
CREATE INDEX idx_case_follow_up_visits_case ON case_follow_up_visits (case_id);
CREATE INDEX idx_case_history_case ON case_history (case_id);
CREATE INDEX idx_case_interventions_case ON case_interventions (case_id);
CREATE INDEX idx_payout_case ON case_payouts (case_id);
CREATE INDEX idx_payout_date ON case_payouts (scheduled_at);
CREATE INDEX idx_payout_status ON case_payouts (status);
CREATE INDEX idx_case_referrals_case ON case_referrals (case_id);
CREATE INDEX idx_case_requirements_case ON case_requirements (case_id);
CREATE UNIQUE INDEX uq_case_requirements_case_key ON case_requirements (case_id, requirement_key);
CREATE INDEX idx_case_step_locks_case ON case_step_locks (case_id);
CREATE INDEX idx_case_control ON cases (control_no);
CREATE INDEX idx_case_status ON cases (status);
CREATE INDEX idx_cases_beneficiary ON cases (beneficiary_id);
CREATE INDEX idx_cases_status_created ON cases (status, created_at);
CREATE INDEX idx_cases_worker ON cases (assigned_worker_id);
CREATE INDEX idx_chat_conversation ON chat_messages (conversation_id);
CREATE INDEX idx_chat_participants ON chat_messages (sender_id, recipient_id);
CREATE INDEX idx_consent_beneficiary ON consent_ledger (beneficiary_id);
CREATE INDEX idx_consent_status ON consent_ledger (status);
CREATE INDEX idx_contact_messages_created_at ON contact_messages (created_at);
CREATE INDEX idx_csr_case ON csr_reports (case_id);
CREATE INDEX idx_csr_control ON csr_reports (control_no);
CREATE INDEX idx_doc_announcement ON document_vault (announcement_id);
CREATE INDEX idx_doc_beneficiary ON document_vault (beneficiary_id);
CREATE INDEX idx_doc_case ON document_vault (case_id);
CREATE INDEX idx_doc_irf ON document_vault (irf_id);
CREATE INDEX idx_hm_household ON household_memberships (household_id);
CREATE INDEX idx_hm_person ON household_memberships (person_id);
CREATE UNIQUE INDEX idx_household_nhts ON households (nhts_pr_id);
CREATE UNIQUE INDEX uq_households_access_card_code ON households (access_card_code);
CREATE INDEX idx_idempotency_key ON idempotency_keys (key);
CREATE INDEX idx_inter_referral_case ON inter_agency_referrals (case_id);
CREATE INDEX idx_inter_referral_from ON inter_agency_referrals (from_agency_id);
CREATE INDEX idx_inter_referral_person ON inter_agency_referrals (person_id);
CREATE INDEX idx_inter_referral_status ON inter_agency_referrals (status);
CREATE INDEX idx_inter_referral_to ON inter_agency_referrals (to_agency_id);
CREATE UNIQUE INDEX uq_intervention_documents ON intervention_required_documents (intervention_type, document_key);
CREATE INDEX idx_irf_created ON irf_cases (created_at);
CREATE INDEX idx_notif_read ON notifications (recipient_id, is_read);
CREATE INDEX idx_notif_recipient ON notifications (recipient_id);
CREATE INDEX idx_office_events_start ON office_events (starts_at);
CREATE INDEX idx_otp_expires ON otp_codes (expires_at);
CREATE INDEX idx_otp_phone ON otp_codes (phone);
CREATE INDEX idx_person_addresses_person ON person_addresses (person_id);
CREATE INDEX idx_person_contacts_person ON person_contacts (person_id);
CREATE INDEX idx_program_enrollments_case ON program_enrollments (case_id);
CREATE INDEX idx_program_funds_program ON program_fund_sources (program_id);
CREATE INDEX idx_program_docs_program ON program_required_documents (program_id);
CREATE INDEX idx_program_services_program ON program_services (program_id);
CREATE INDEX idx_referral_barangay ON referrals (barangay);
CREATE INDEX idx_referral_coordinator ON referrals (coordinator_id);
CREATE INDEX idx_referral_person ON referrals (person_id);
CREATE INDEX idx_referral_status ON referrals (status);
CREATE INDEX idx_sync_device ON sync_queue (device_id);
CREATE INDEX idx_sync_device_idemp ON sync_queue (device_id, idempotency_key);
CREATE INDEX idx_sync_status ON sync_queue (status);
CREATE INDEX idx_team_invites_to_status ON team_invites (to_user_id, status);
CREATE INDEX idx_blocks_source_ref ON team_schedule_blocks (source_ref);
CREATE INDEX idx_team_blocks_user_date ON team_schedule_blocks (user_id, block_date);
CREATE INDEX idx_user_barangay_user ON user_barangay_assignments (user_id);
CREATE INDEX idx_user_tokens_user ON user_tokens (user_id);
CREATE INDEX idx_user_agency ON users (agency_id);
CREATE INDEX idx_user_person ON users (person_id);

-- Indexes that PostgreSQL supports and plain Oracle DDL does not.
-- Left as comments so nothing is lost and the import still parses.

-- CREATE INDEX idx_person_name_trgm ON persons USING gin (surname gin_trgm_ops, first_name gin_trgm_ops)
--   ^ GIN/GiST index: no Oracle equivalent in plain DDL; use Oracle Text / a function-based index instead.

-- CREATE INDEX idx_person_search ON persons USING gin (search_vector)
--   ^ GIN/GiST index: no Oracle equivalent in plain DDL; use Oracle Text / a function-based index instead.

-- CREATE UNIQUE INDEX uq_reminder_system_type ON reminder_settings USING btree (event_type) WHERE ((scope)::text = 'system'::text)
--   ^ PostgreSQL partial index. Oracle has no partial indexes; the predicate
--     ((scope)::text = 'system'::text)
--     would have to become a function-based index.

-- CREATE UNIQUE INDEX uq_reminder_worker_type ON reminder_settings USING btree (user_id, event_type) WHERE ((scope)::text = 'worker'::text)
--   ^ PostgreSQL partial index. Oracle has no partial indexes; the predicate
--     ((scope)::text = 'worker'::text)
--     would have to become a function-based index.

-- CREATE UNIQUE INDEX uq_team_invites_pending ON team_invites USING btree (from_user_id, to_user_id, invite_date) WHERE ((status)::text = 'pending'::text)
--   ^ PostgreSQL partial index. Oracle has no partial indexes; the predicate
--     ((status)::text = 'pending'::text)
--     would have to become a function-based index.
